remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

title: [breadBakingFoam official page]
description: [breadBakingFoam is a software for simulation of the bread baking process]

include:
  - assets
